### ISSUE TITLE
Rewrite readme

### ISSUE THREAD

**Issue by Asgoret** [pyToshka/openshift-vagrant#11]
- [x] Add part about brokers
- [x] Add part about switching runtime
- [x] Add part about names in vagrant provisioner
- [x] Add part about backup script
- [x] Add part about vagrant variables
- [x] Add part about OKD variables

**Comment by pyToshka** [comment]
Also need to review current Readme and remove extra sentences and add variables for vagrant

**Comment by Asgoret** [comment]
https://github.com/pyToshka/openshift-vagrant/pull/25
