### ISSUE TITLE
Сontainer images are not available

### ISSUE THREAD

**Issue by Uttah** [pyToshka/openshift-vagrant#30]
**Describe the bug**
After vagrant up I get this:
1. Hosts:    okd-master1
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required container images are not available:
                   docker.io/openshift/origin-docker-registry:v3.11.0,
                   docker.io/openshift/origin-haproxy-router:v3.11.0,
                   docker.io/openshift/origin-pod:v3.11.0,
                   quay.io/coreos/etcd:v3.2.22
               Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>

**To Reproduce**
vagrant up from master or development branch

**Screenshots**
<img width="897" alt="Снимок экрана 2019-03-14 в 10 14 36" src="https://user-images.githubusercontent.com/31721839/54335304-fa706800-4641-11e9-8718-33715cdf8f4f.png">

**Comment by Asgoret** [comment]
@Uttah you have full access to the internet? And what branch do you use?)

**Comment by Uttah** [comment]
> @Uttah you have full access to the internet? And what branch do you use?)

Full access. Master branch and development branch.
Macos Mojave, 8Gb.

**Comment by Asgoret** [comment]
@Uttah VM is needed 8GB it's failure

I`ll try on my mac. Works fine. Issue сurrency?
